# fly.toml app configuration file generated for voxta on 2024-12-01T00:10:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voxta'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  DEBIAN_FRONTEND = 'noninteractive'

[[mounts]]
  source = 'voxta_data'
  destination = '/app/Data'
  initial_size = '1gb'

[http_service]
  internal_port = 5384
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
