[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  DEBIAN_FRONTEND = 'noninteractive'

[[mounts]]
  source = 'voxta_data'
  destination = '/app/Data'
  initial_size = '1gb'

[http_service]
  internal_port = 5384
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
